### ISSUE TITLE
Dependencies 

### ISSUE THREAD

**Issue by WLaney** [sharkduino/sharkduino_R_analysis#1]
How do we want to handle required packages for the analysis code? Would it make sense to have the needed packages stored and installed locally in this repository, or would that make things to unwieldy? I don't know how dependencies are normally managed, is there some simple solution to this that I just don't know?

**Comment by d9i** [comment]
We could store our packages locally, but that seems unnecessary to me: other contributors can get all the necessary packages by running
```
install.packages("ggplot2")
install.packages("psd")
install.packages("signal")
install.packages("seewave")
install.packages("viridis")
```
Looking forward to the "releasing our code as an R package" case, R packages should automatically install their dependencies when installed, so we ought to be good on that front.

If you want, I could also maintain an install script (just those `install.packages` lines, but in a .R file) so people can get started more easily, but it's a 5 minute job installing them manually, so it wouldn't be a huge difference.

**Comment by WLaney** [comment]
I think that the best option is to maintain an install script.

Right now we only need five packages, but as we write more scripts that number can easily grow. It would be inconvenient to have to open up a bunch of scripts and look at what packages they require ever time we want to do the analysis on another machine. Also an install script make the code easer to use for people without much R experience. 

Another problem we should keep in mind is package versions. I don't think this should be much of an issue, but we should keep it in the back of our mind. If a package update breaks our code we can worry more about it then.
