### ISSUE TITLE
Data analysis: ax data asymmetry

### ISSUE THREAD

**Issue by d9i** [sharkduino/sharkduino_R_analysis#14]
In the 20170828_22c_Viseryon_Part_1 dataset, the accelerometer X dataset is centered on 1 (because of acceleration due to gravity). 

However, disturbances in this dataset are highly asymmetrical, veering closer to 0Gs and rarely rising above 1G. We need to figure out why this is, and whether this is normal.

Here's a picture that illustrates what I'm talking about:
<img width="1143" alt="screen shot 2017-10-09 at 4 33 28 pm" src="https://user-images.githubusercontent.com/1351693/31357433-b8d7a998-ad0f-11e7-924b-cce9f8fd1a39.png">

**Comment by WLaney** [comment]
Does the Z axis look like this? Can you check Sharkduino and GCDC datasets?

**Comment by d9i** [comment]
The Z axis is centered near 0, and doesn't really look like that. A picture is attached.

As for other datasets, I checked 20170828_21a_other_shark, and it looks like the same thing is happening there. Stay tuned for other datasets + GCDC.

<img width="1328" alt="screen shot 2017-10-10 at 9 54 53 pm" src="https://user-images.githubusercontent.com/1351693/31418717-b70a3ea4-ae05-11e7-8072-b4d7f6fadb11.png">

**Comment by d9i** [comment]
20170822_21b_other_shark has the same thing happening.

I have a theory that this may be caused by the shark corkscrewing of flipping, such that the gravity is no longer in x. I'm going to try to test this by comparing the other accelerometer axes

**Comment by d9i** [comment]
yeah, looks like it's barrel rolls. Case closed, I think
