### ISSUE TITLE
Modify importer to handle skipped gyroscope reads

### ISSUE THREAD

**Issue by TheBen27** [sharkduino/sharkduino_R_analysis#2]
The main way to reduce gyroscope power consumption is to turn the device off. In the CSV file generated by my parser, "skipped" gyroscope reads are represented through blank cells.

Since skipped reads will be part of the project going forward, the importer (and code using imported data) should be able to handle them.

**Comment by TheBen27** [comment]
Here's some test data
[test-gskp.zip](https://github.com/WLaney/sharkduino_R_analysis/files/769730/test-gskp.zip)

**Comment by d9i** [comment]
I just saw this - 2 months late. Will do!

**Comment by d9i** [comment]
Done in commit 18a86f34514a1104d084309d3acb51e4cea5c09a
