### ISSUE TITLE
Correct Orientation by Tag Name

### ISSUE THREAD

**Issue by TheBen27** [sharkduino/sharkduino_R_analysis#3]
2.0 hardware tags have an incorrect orientation.
To correct against this, you can use the tag name given in header.csv (or ask the user for it if need be) - the first character will be the tag's major version
![sharkduino orientation drawing](https://cloud.githubusercontent.com/assets/1351693/25066445/8a63e09c-21f3-11e7-8091-82959bfc04e1.jpg)

**Comment by d9i** [comment]
functionality added in commit 0f3f51ee2309ebe1fcaf7fb2d1bc657a0a61c6c9 :D
